### ISSUE TITLE
This project has been marked as deprecated and is not recommended for use anymore.

### ISSUE THREAD

**Issue by 9renpoto** [lukechilds/browser-env#35]
- https://libraries.io/npm/browser-env

`browser-env` package is deprecated ?
Currently troubled by warning from https://dependencyci.com .

**Comment by lukechilds** [comment]
Hmmn, I'm not quire sure why it's showing up as deprecated, I haven't deprecated it.

Thanks for bringing it to my attention, I'm looking in to it now.

**Comment by lukechilds** [comment]
I've just manually un-deprecated by deprecating with an empty string:

```
npm deprecate browser-env ""
```

Even though I'm pretty sure it wasn't deprecated. I've also just published a new patch version to make sure. If I install I don't get any deprecations warnings in the terminal.

I have a hunch this may actually be a bug with libraries.io/dependencyci.com. I have deprecated specific versions in the past with known bugs. It looks like this is possibly being interpreted as the entire package being deprecated which is incorrect. I'll wait until libraries.io picks up the new version and see what it says.

**Comment by 9renpoto** [comment]
Thank you for your investigation !
I'm waiting for good results.

**Comment by lukechilds** [comment]
Yeah, libraries.io are still saying the latest version is deprecated :/

I've notified both libraries.io and dependencyci.com. Lets see what they say :)

https://github.com/librariesio/libraries.io/issues/1247
https://github.com/dependencyci/support/issues/81

**Comment by andrew** [comment]
I've fixed that for you, thanks for letting me know

**Comment by lukechilds** [comment]
@9renpoto Should be all good now.

**Comment by 9renpoto** [comment]
Perfect ! Thank you !
