### ISSUE TITLE
English prose filenames are causing problems with flow-typed

### ISSUE THREAD

**Issue by mimshwright** [lukechilds/browser-env#42]
Specifically having spaces and apostrophes in the filenames. Understandably this is a problem with flow-typed more than your library, however, since this naming convention is more of a clever trick than a serious feature, perhaps you will consider fixing it on this end.

See this issue from flow-typed 
https://github.com/flowtype/flow-typed/issues/673

**Comment by lukechilds** [comment]
Thanks for brining this to my attention, I had no idea. I assume just adding `test` to `.npmignore` should resolve the problem, right?

**Comment by lukechilds** [comment]
Just published v2.0.31 without the test dir. I've not used flow-typed before and I'm not too familiar with how to set it up. Would you mind pulling down the latest version of browser-env and letting me know if the issue is resolved?

**Comment by lukechilds** [comment]
@mimshwright Just published v2.0.31 without the test dir. I've not used flow-typed before and I'm not too familiar with how to set it up. Would you mind pulling down the latest version of browser-env and letting me know if the issue is resolved?

**Comment by mimshwright** [comment]
That seems to have fixed the issue! thank you.
