### ISSUE TITLE
Expose the JSDOM instance

### ISSUE THREAD

**Issue by avaly** [lukechilds/browser-env#49]
In certain cases it's useful to have access to the JSDOM instance in order to [reconfigure](https://github.com/tmpvar/jsdom#reconfiguring-the-jsdom-with-reconfiguresettings).

Example:
- setup `browserEnv` globally in the unit tests setup script with a default URL
- some tests within the test suite might need to have different URLs for the window

**Comment by lukechilds** [comment]
If you need a different environment in each test then you should probably be using [`window`](https://github.com/lukechilds/window) or just jsdom directly.

`browserEnv` is global so if you have tests running async then they're gonna be reconfiguring stuff for each other.
