### ISSUE TITLE
Cleanup or Remove Globals?

### ISSUE THREAD

**Issue by mAAdhaTTah** [lukechilds/browser-env#57]
Is it possible to cleanup or otherwise undo the effects of calling `browserEnv`?

**Comment by lukechilds** [comment]
Undo isn't really possible because `browserEnv` can be called multiple times and we don't know what state `global` was in before it was called each time.

I could definitely add a clean method though, which would just delete all browser like variables.

**Comment by lukechilds** [comment]
I'm happy to add this but I'm very busy at the moment so won't be able to work on it for a while. A PR would be great if you want to work on this.

**Comment by lukechilds** [comment]
On second thoughts, I don't really think there's a reliable way to implement this.

I think it would best to consider the process a sort of franken-browser environment once `browser-env` has been called.

If you want to set specific global variables for browser functionality and then clean up after yourself you should implement this behaviour on top of [`window`](https://github.com/lukechilds/window).
