### ISSUE TITLE
Testing DOM events

### ISSUE THREAD

**Issue by argyleink** [lukechilds/browser-env#67]
I don't see a way to test events. Do I need to tap into jsDOM?

**Comment by lukechilds** [comment]
I'm not sure exactly what you mean by testing events, can you provide some example code?

**Comment by argyleink** [comment]
i'm writing this test https://github.com/argyleink/blingblingjs/blob/master/src/index.test.js#L119

I've tried a few things, but here's generally what I think I need and have setup:
```
test.cb('$("button").on("click", e => ...)', t => {
  const btn = document.createElement('button')
  document.body.appendChild(btn)

  $('button').on('click mouseover', t.end)
  // btn.click()

  // found this googling
  let evt = document.createEvent('test')
  evt.initEvent('click', false, true)
  btn.dispatchEvent(evt)

  // found this googling
  let event = new window.Event("click")
  btn.dispatchEvent(event)
})
```

`t.end()` is never called, I'm trying to get it to call, not sure how to make that happen with ava and browser-env 🤓

**Comment by lukechilds** [comment]
Have you tested that code works in a browser? (without the AVA specific bits)

**Comment by argyleink** [comment]
easiest method does

![screen shot 2018-04-03 at 9 57 57 pm](https://user-images.githubusercontent.com/1134620/38289219-068499a8-378a-11e8-8d2b-8c9b064355ea.png)

**Comment by argyleink** [comment]
guess what's dumb but sweet, there's no bug, it's just jsdom and buttons.. code works fine, but it wont fire for buttons added to the document lol. i don't care why, just glad i decided to try another element.
