### ISSUE TITLE
Export a `register` sub-module

### ISSUE THREAD

**Issue by sindresorhus** [lukechilds/browser-env#68]
So we can add `browser-env` directly to test files using a `--register` function.

For example, with AVA, I could use this config:

```js
"ava": {
	"require": [
		"browser-env/register"
	]
}
```

Then I wouldn't need to import `browser-env` in each test file.

The `register.js` file would just contain:

```js
'use strict';
const browserEnv = require('browser-env');

browserEnv();
```

---

Example: https://github.com/sindresorhus/unstated-debug/pull/1/files#diff-138b35eb5741965511c50dc306577927R1

**Comment by dy** [comment]
Would be really nice to have that implemented.
Workaround for now to run tests in node

```sh
node -r esm -r ./test/register.js test/index.js
```
where `register.js` contains what @sindresorhus showed.
