### ISSUE TITLE
SNYK warning on browser-env

### ISSUE THREAD

**Issue by nothingismagick** [lukechilds/browser-env#74]
✗ Medium severity vulnerability found in content-type-parser
  Description: Regular Expression Denial of Service (ReDoS)
  Info: https://snyk.io/vuln/npm:content-type-parser:20170905
  Introduced through: browser-env@3.2.5
  From: browser-env@3.2.5 > window@4.2.5 > jsdom@11.6.2 > content-type-parser@1.0.2

Please consider updating to window@4.2.6 to bring jsdom@13.2.0 which apparently removes conten-type-parser entirely.

**Comment by lukechilds** [comment]
Fixed and published as `browser-env@3.2.6`, thanks for letting me know!
